# Generated by Django 5.0.3 on 2024-05-14 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('phoneno', models.CharField(default='', max_length=100)),
                ('address_line_1', models.TextField(default='')),
                ('address_line_2', models.TextField(default='')),
                ('city', models.TextField(default='', max_length=100)),
                ('state', models.TextField(default='', max_length=50)),
                ('pincode', models.PositiveBigIntegerField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
